# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
s.split(' ')

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [4]:
planet = "Earth"
diameter = 12742

In [5]:
print( 'The diameter of {} is {} kilometers.' .format(planet,diameter));

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [6]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [7]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [10]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [11]:
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [13]:
import numpy as np
array=np.arange(20,35,2)
print("Array of all the even integers from 20 to 35")
print(array)

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [15]:
import numpy as np

a = np.array([1, 2, 3])

b= np.array([4, 5, 6])

arr = np.concatenate((a, b))
arr

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [16]:
import pandas as pd


In [17]:
di = {'a': [1, 'df1'],'b': [2, 'df2'],'c': [3, 'df3']}
df = pd.DataFrame(di)
df


a    b    c
0    1    2    3
1  df1  df2  df3

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [18]:
di = {'a': [1, 'df1'],'b': [2, 'df2'],'c': [3, 'df3']}
df = pd.DataFrame(di)
df


a    b    c
0    1    2    3
1  df1  df2  df3

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [19]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [20]:
df = pd.DataFrame(lists)
df


0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24