# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
print(s.split())

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
print(f"The diameter of {planet} is {diameter} kilometres.")

The diameter of Earth is 12742 kilometres.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
zeros = np.zeros(10)

In [ ]:
fives = np.full(10,5)
print(zeros,fives)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [5 5 5 5 5 5 5 5 5 5]


## 5. Create an array of all the even integers from 20 to 35

In [ ]:
arr=[i for i in range(20,35+1) if i%2==0]
arr

[20, 22, 24, 26, 28, 30, 32, 34]

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
array=np.arange(0,9).reshape((3,3))
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c=np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd

In [ ]:
d={'name':['raj','jhon','joe'],'age':[21,26,28]}
df=pd.DataFrame.from_dict(d)
df

name  age
0   raj   21
1  jhon   26
2   joe   28

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
date=pd.date_range("01-01-2023","10-02-2023",freq="D")

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:

df=pd.DataFrame(lists,columns=["C1","C2","C3"])
df

C1   C2  C3
0   1  aaa  22
1   2  bbb  25
2   3  ccc  24